apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: devops-platform
    component: frontend
spec:
  type: LoadBalancer
  selector:
    app: devops-platform
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
